services:
  mysql:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - database:/var/lib/mysql
    # ports:
    #   - "3306:3306"
    healthcheck:  
      test: ["CMD", "mysqladmin", "ping", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:latest
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    # To increase max upload size to 512M:
    # docker exec -it -u 0 projet-info-adminer-1 sed -i.bak -E 's/^(upload_max_filesize[[:space:]]*=[[:space:]]*).*/\1512M/; s/^(post_max_size[[:space:]]*=[[:space:]]*).*/\1512M/' /usr/local/etc/php/conf.d/0-upload_large_dumps.ini

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    depends_on:
      - mysql
    volumes:
      - grafana:/var/lib/grafana
    ports:
      - "3002:3000"

  crawler:
    image: ghcr.io/oetgin/projet-info:crawler-latest
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy

  model:
    image: ghcr.io/oetgin/projet-info:model-latest
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  database:
  grafana: