name: Docker Image CI

on:
  push:
    branches: [ "refactoring" ]

jobs:

  build:
    name: Build the Docker images of the project
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      
    steps:
    - uses: actions/checkout@v6

    - name: Build crawler
      run: docker build ./crawler/ -t ghcr.io/oetgin/projet-info:crawler-latest

    # - name: Build model
    #   run: docker build ./model/ -t ghcr.io/oetgin/projet-info:model-latest

    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push crawler image
      run: docker push ghcr.io/oetgin/projet-info:crawler-latest

    # - name: Push model image
    #   run: docker push ghcr.io/oetgin/projet-info:model-latest

      